# Generated by Django 5.2 on 2025-04-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeDislike',
        ),
    ]
