# Generated by Django 5.1.4 on 2025-05-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('organisation', 'Organisation')], max_length=20, null=True),
        ),
    ]
