# Generated by Django 5.1.4 on 2025-05-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('organisation', 'Organisation')], max_length=20),
        ),
    ]
