# Generated by Django 5.1.4 on 2025-05-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('organisation', 'Organisation')], default='user', max_length=20, null=True),
        ),
    ]
